// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var welcome = Welcome.FromJson(jsonString);

namespace NetMo.Util
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class NetAtmoResponse
    {
        [JsonProperty("body")]
        public Body Body { get; set; }

        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("time_exec")]
        public double TimeExec { get; set; }

        [JsonProperty("time_server")]
        public long TimeServer { get; set; }

        private static NetAtmoResponse lastResp;
        public static NetAtmoResponse LastResponse
        {
            get
            {
                return lastResp;
            }
        }

        public NetAtmoResponse()
        {
            lastResp = this;
        }
    }

    public partial class Body
    {
        [JsonProperty("devices")]
        public Device[] Devices { get; set; }

        [JsonProperty("user")]
        public User User { get; set; }
    }

    public partial class Device
    {
        [JsonProperty("_id")]
        public string Id { get; set; }

        [JsonProperty("cipher_id")]
        public string CipherId { get; set; }

        [JsonProperty("date_setup")]
        public long DateSetup { get; set; }

        [JsonProperty("last_setup")]
        public long LastSetup { get; set; }

        [JsonProperty("type")]
        public string Type { get; set; }

        [JsonProperty("last_status_store")]
        public long LastStatusStore { get; set; }

        [JsonProperty("module_name")]
        public string ModuleName { get; set; }

        [JsonProperty("firmware")]
        public long Firmware { get; set; }

        [JsonProperty("last_upgrade")]
        public long LastUpgrade { get; set; }

        [JsonProperty("wifi_status")]
        public long WifiStatus { get; set; }

        [JsonProperty("reachable")]
        public bool Reachable { get; set; }

        [JsonProperty("co2_calibrating")]
        public bool Co2Calibrating { get; set; }

        [JsonProperty("station_name")]
        public string StationName { get; set; }

        [JsonProperty("data_type")]
        public string[] DataType { get; set; }

        [JsonProperty("place")]
        public Place Place { get; set; }

        [JsonProperty("dashboard_data")]
        public DeviceDashboardData DashboardData { get; set; }

        [JsonProperty("modules")]
        public Module[] Modules { get; set; }
    }

    public partial class DeviceDashboardData
    {
        [JsonProperty("time_utc")]
        public long TimeUtc { get; set; }

        [JsonProperty("Temperature")]
        public double Temperature { get; set; }

        [JsonProperty("CO2")]
        public long Co2 { get; set; }

        [JsonProperty("Humidity")]
        public long Humidity { get; set; }

        [JsonProperty("Noise")]
        public long Noise { get; set; }

        [JsonProperty("Pressure")]
        public double Pressure { get; set; }

        [JsonProperty("AbsolutePressure")]
        public double AbsolutePressure { get; set; }

        [JsonProperty("min_temp")]
        public double MinTemp { get; set; }

        [JsonProperty("max_temp")]
        public double MaxTemp { get; set; }

        [JsonProperty("date_min_temp")]
        public long DateMinTemp { get; set; }

        [JsonProperty("date_max_temp")]
        public long DateMaxTemp { get; set; }

        [JsonProperty("temp_trend")]
        public string TempTrend { get; set; }

        [JsonProperty("pressure_trend")]
        public string PressureTrend { get; set; }
    }

    public partial class Module
    {
        [JsonProperty("_id")]
        public string Id { get; set; }

        [JsonProperty("type")]
        public string Type { get; set; }

        [JsonProperty("module_name")]
        public string ModuleName { get; set; }

        [JsonProperty("data_type")]
        public string[] DataType { get; set; }

        [JsonProperty("last_setup")]
        public long LastSetup { get; set; }

        [JsonProperty("reachable")]
        public bool Reachable { get; set; }

        [JsonProperty("dashboard_data")]
        public ModuleDashboardData DashboardData { get; set; }

        [JsonProperty("firmware")]
        public long Firmware { get; set; }

        [JsonProperty("last_message")]
        public long LastMessage { get; set; }

        [JsonProperty("last_seen")]
        public long LastSeen { get; set; }

        [JsonProperty("rf_status")]
        public long RfStatus { get; set; }

        [JsonProperty("battery_vp")]
        public long BatteryVp { get; set; }

        [JsonProperty("battery_percent")]
        public long BatteryPercent { get; set; }
    }

    public partial class ModuleDashboardData
    {
        [JsonProperty("time_utc")]
        public long TimeUtc { get; set; }

        [JsonProperty("Temperature")]
        public double Temperature { get; set; }

        [JsonProperty("Humidity")]
        public long Humidity { get; set; }

        [JsonProperty("min_temp")]
        public double MinTemp { get; set; }

        [JsonProperty("max_temp")]
        public double MaxTemp { get; set; }

        [JsonProperty("date_min_temp")]
        public long DateMinTemp { get; set; }

        [JsonProperty("date_max_temp")]
        public long DateMaxTemp { get; set; }

        [JsonProperty("temp_trend")]
        public string TempTrend { get; set; }

        [JsonProperty("CO2", NullValueHandling = NullValueHandling.Ignore)]
        public long? Co2 { get; set; }
    }

    public partial class Place
    {
        [JsonProperty("altitude")]
        public long Altitude { get; set; }

        [JsonProperty("city")]
        public string City { get; set; }

        [JsonProperty("country")]
        public string Country { get; set; }

        [JsonProperty("timezone")]
        public string Timezone { get; set; }

        [JsonProperty("location")]
        public double[] Location { get; set; }
    }

    public partial class User
    {
        [JsonProperty("mail")]
        public string Mail { get; set; }

        [JsonProperty("administrative")]
        public Administrative Administrative { get; set; }
    }

    public partial class Administrative
    {
        [JsonProperty("lang")]
        public string Lang { get; set; }

        [JsonProperty("reg_locale")]
        public string RegLocale { get; set; }

        [JsonProperty("unit")]
        public long Unit { get; set; }

        [JsonProperty("windunit")]
        public long Windunit { get; set; }

        [JsonProperty("pressureunit")]
        public long Pressureunit { get; set; }

        [JsonProperty("feel_like_algo")]
        public long FeelLikeAlgo { get; set; }
    }

    public partial class Welcome
    {
        public static Welcome FromJson(string json) => JsonConvert.DeserializeObject<Welcome>(json, Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this Welcome self) => JsonConvert.SerializeObject(self, Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}